title: "Verinin Gerçekliği"
description: "Veri ile gerçekliğe uzanan bir yolculuk."

# Tema
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "air"

# Gerekli pluginler
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

markdown: kramdown

# Yazar Bilgisi
author:
  name: "Nurgül Evcim"
  bio: "Ekonomi, veri analizi ve müşteri içgörüleri alanında çalışan bir veri odaklı araştırmacı."
  location: "Türkiye"

# BLOG AYARLARI
paginate: 5
paginate_path: "/blog/page:num/"

# Post koleksiyonu — KATEGORİYE GÖRE URL
collections:
  posts:
    output: true
    permalink: /:categories/:title/

# KATEGORİ & TAG ARŞİVLERİ (⭐ zorunlu)
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Varsayılanlar (ÇOK KRİTİK)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      read_time: true
      comments: false
