title: "Verinin Gerçekliği"
description: "Veri ile gerçekliğe uzanan bir yolculuk."

remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

markdown: kramdown

author:
  name     : "Nurgül Evcim"
  bio      : "Ekonomi, veri analizi ve müşteri içgörüleri alanında çalışan bir veri odaklı araştırmacı."
  location : "Türkiye"

# ✔ BLOG İÇİN GEREKLİ AYARLAR
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  posts:
    output: true
    permalink: /:categories/:title/

defaults:
  # Sayfalar
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single

  # Postlar (blog yazıları)
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      read_time: true
      comments: false
